FROM sacbase/sac-compiler:latest

# Install SaC energy measuring library
RUN git clone --depth 1 --single-branch --recursive https://github.com/SacBase/sac-energy.git \
 && cd sac-energy \
 && make

# Install dynamic adaptation controller
ADD https://github.com/JordyAaldering/ecodynamic/releases/download/main/server /usr/local/bin/ecodynamic
RUN chmod +x /usr/local/bin/ecodynamic

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

WORKDIR /home
