FROM debian:trixie-slim

# Install dynamic adaptation controller
ADD https://github.com/JordyAaldering/ecodynamic/releases/download/main/server /usr/local/bin/ecodynamic
RUN chmod +x /usr/local/bin/ecodynamic

# Start server
ENTRYPOINT ["ecodynamic"]
