FROM rust:latest

# Install dynamic adaptation controller
RUN curl https://github.com/JordyAaldering/ecodynamic/releases/download/main/server > /usr/local/bin/ecodynamic \
 && chmod +x /usr/local/bin/ecodynamic

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

WORKDIR /home
