name: docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [rust, sac]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: docker/setup-buildx-action@v3
    - name: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        file: Dockerfile.${{ matrix.variant }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecodynamic:${{ matrix.variant }}
        push: true
